### ISSUE TITLE
eip1559 integration

### ISSUE THREAD

**Issue by thegostep** [flashbots/mev-geth#70]

**Comment by pgebheim** [comment]
The current PR for 1559 from geth -- https://github.com/ethereum/go-ethereum/pull/22896

Mev-Geth Tasks:
- Investigate if Ethers handles 1559 encoding for tests (T/J)
- figure out how running eip-1599 in a local test net even works, ie. can we easily control the basefee in the header (T/J)
- update end to end tests to use eip-1559 tests (T/J)
  - Make sure we enable the london fork
- mev-geth load test - update to support 1559 (T/J)
- Add test cases for consensus changes:
  - There is a new rule added friday, we may need to check that things work,
  - sender balancer is greater than maxFeePerGas*gasLimit
  - priority fee per gas <= max fee per gas
- add test for bundle with a tx below the block header basefee

- update sponsored tx to rely on pre-inbound eth instead of post-payment of 0-gas-price (J)
- eth_callBundle updates (J)
  - Update gas price
  - Use new fee tip
  - Check base fee

Relay Changes:
- Almost nothing should need to change here.
- Update the hard cutoff for gas price (gasnow endpoint, hardcoded value)

Not mev-geth:
- Update blocks api
- Survey miners and asking if they're planning on moving forward with EIP1559 (Tomasz/Tina?)
  - Is there anything they require us to deliver?

Timeline:
- Original geth timeline was pushed because of a consensus, so Friday the 11th the timelines will be decided on.
- For our planning
 - 14/15th a likely date first testnet to exist -- could be delayed.
 - 15th of July is earliest date for mainnet
 - Goerli Date ~~ 23rd of June

Testing:
- Been relying on end-to-end tests
- Could revisit trying to do more unit test -- it's very complicated
- Investigate connecting mev-geth as a validator to Calaveras (end to end)

Discussion Future Notes:
- Add better End to End testing Structure
- Research: Are there efficient ways to capture value by arbing between legacy and eip1559 txn

**Comment by pgebheim** [comment]
Spec: https://hackmd.io/X3tu9m0PRx23IGS93Qy9SA

Proposed release plan: https://hackmd.io/KIDv3kMTSxmM1WHO_IUqIA

**Comment by tqpcharlie** [comment]
any update on this?

**Comment by tqpcharlie** [comment]
#80

**Comment by pgebheim** [comment]
Yes,

The implementation changes here -- https://github.com/flashbots/mev-geth/tree/release/v1.10.4-mev0.3. This has been deployed to Goerli and has been running since the Goerli switchover to london.

**Comment by jparyani** [comment]
Newest branch is based on upstream v1.10.5, https://github.com/flashbots/mev-geth/tree/release/v1.10.5-mev0.3. Also it has been pushed to master.
